name: Upstream Synchronization

on:
  schedule:
    - cron:  '0 0 * * 0,3'
    # scheduled at 0:00 every Sunday and Wednesday

jobs:
  sync_with_upstream:    
    runs-on: ubuntu-latest
    steps:
      - name: forkbacon
      - uses: actions/checkout@v2
      - uses: shitiomatic/forkbacon@1.1.0 # Prefer using tagged version
        with:
          upstream_url: "https://github.com/postgres/pgadmin4.git" # Required! Upstream https clone URL
          upstream_branch: "master"   # Upstream Branch to use
          branch: "master"   # Local Branch
          method: "rebase"   # Method to use. Can be `merge`, `merge-ff-only` or `rebase`.
          args: "--no-push"  # Additional Arguments to pass to the container

      - name: Timestamp
        run: date
